### ISSUE TITLE
Import error #2

### ISSUE THREAD

**Issue by Igor-987** [abess-team/abess#285]
When I import abess in my python file, I see the following error:

Traceback (most recent call last):
  File "c:\Users\igork\code\best_subset.py", line 1, in <module>
    from abess.linear import abessLm
  File "C:\Users\igork\AppData\Roaming\Python\Python39\site-packages\abess\__init__.py", line 9, in <module> 
    from abess.linear import abessLogistic, abessLm, abessCox, abessPoisson, abessMultigaussian, abessMultinomial, abessGamma
  File "C:\Users\igork\AppData\Roaming\Python\Python39\site-packages\abess\linear.py", line 3, in <module>   
    from .bess_base import bess_base
  File "C:\Users\igork\AppData\Roaming\Python\Python39\site-packages\abess\bess_base.py", line 6, in <module>
    from .cabess import *
  File "C:\Users\igork\AppData\Roaming\Python\Python39\site-packages\abess\cabess.py", line 13, in <module>  
    from . import _cabess
ImportError: DLL load failed while importing _cabess: Не найден указанный модуль.

I tried installing MinGW-w64 and adding it to PATH as written here https://github.com/abess-team/abess/issues/259 : but the problem persists.

abess was installed via pip install. python version 3.9.6
Can you help me?

**Comment by Jiang-Kangkang** [comment]
Hi~Have you installed the dependencies include swig, bash and  mingw? Please follow the [guideline](https://abess.readthedocs.io/en/latest/Installation.html) to install the dependencies first. If this problem still occurs, feel free to contact us.

**Comment by Jiang-Kangkang** [comment]
We have fix this problem in latest Python package. If you have any other problem, feel free to contact us. We will close  this issue.
